#' @title Example SingleTimeSeries dataset
#' @format An S3 object composed of "meta" and "data" dataframes.
#' @description The \code{example_sts} dataset provides a quickly loadable
#' version of an \emph{sts} object for practicing and code examples.
#'
#' This dataset was was generated on 2021-01-08 by running:
#'
#' \preformatted{
#' library(AirSensor)
#'
#' example_sts <- example_pat
#' example_sts$meta$elevation <- as.numeric(NA)
#' example_sts$meta$locationName <- example_sts$meta$label
#'
#' save(example_sts, file = "data/example_sts.rda")
#' }
"example_sts"


#' @title Example MultipleTimeSeries dataset
#' @format An S3 object composed of "meta" and "data" dataframes.
#' @description The \code{example_mts} dataset provides a quickly loadable
#' version of a \emph{mts} object for practicing and code examples.
#'
#' This dataset was was generated on 2021-10-07 by running:
#'
#' \preformatted{
#' library(AirSensor)
#'
#' communities <- c("Alhambra/Monterey Park", "El Monte")
#'
#' example_mts <-
#'   example_sensor_scaqmd %>%
#'   sensor_filterMeta(communityRegion %in% communities)
#'
#' # Add required "locationName"
#' example_mts$meta$locationName <- example_mts$meta$siteName
#'
#' save(example_mts, file = "data/example_mts.rda")
#' }
"example_mts"

#' @title Example RAWS dataset
#' @format An S3 object composed of "meta" and "data" dataframes.
#' @description The \code{example_raws} dataset provides a quickly loadable
#' example of the data generated by the **RAWSmet** package. This data is a
#' \code{sts} object containing hourly measurements from a RAWS weather station
#' in Saddle Mountain, WA, between July 2002 and December 2017.
#'
#' This dataset was was generated on 2021-02-25 by running:
#'
#' \preformatted{
#' library(RAWSmet)
#'
#' setRawsDataDir("~/Data/RAWS")
#'
#' example_raws <- fw13_load(nwsID = "452701")
#'
#' save(example_raws, file = "data/example_raws.rda")
#' }
"example_raws"

